name: bioscape-gra
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7.3
  - pip
  # Core scientific python
  - numpy
  - pyqt
  - tqdm
  - kiwisolver
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn

  # Spatial packages
  - pysal
  - pyproj>=3.0
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - rioxarray>=0.3.0
  - scikit-learn
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask
